config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users 

  resources :games

  resources :player_games

  resources :courts

  resources :user_reviews

  resources :skills

  resources :player_skills
 
  resources :welcome, :only => [:new, :create]


  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'
  post '/sessions' => 'sessions#create'

  root 'player_games#show'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
require 'rest-client'
require 'json'



class Court < ApplicationRecord
    has_many :games

    def self.chicago_ball_parks
        response_string = RestClient.get('https://data.cityofchicago.org/resource/y7qa-tvqx.json')
        response_hash = JSON.parse(response_string)

        park = response_hash

        basketball_court = []

        park.each do |park_hash|
            if park_hash["facility_name"] == "BASKETBALL COURT"
                # x = park_hash["location"]["latitude"]
                # y = park_hash["location"]["longitude"]
                basketball_court << park_hash["park"] 
            end
        end
        basketball_court.uniq
    end

end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :court, optional: true
    belongs_to :user, :foreign_key => "host_id", optional: true

    has_many :player_games
    has_many :players, :class_name => 'User', through: :player_games


    validates :name, uniqueness: true
    validates :name, :date, :player_count, presence: true
    validates :player_count, numericality: { greater_than: 1}
   

    def clean_date

        date = self.date

        date.strftime("%a, %d %b %Y")
    end

    def clean_time
        time = self.time

        time.strftime("%r")
    end

    def pg_count
        
        self.players.size + 1
    end

    def players_left
        self.player_count - self.pg_count
    end

end

app/models/player_game.rb
class PlayerGame < ApplicationRecord
    belongs_to :player, :class_name => "User"
    belongs_to :game 

    validates :player_id, presence: true, :uniqueness => 
    { :scope => :player_id, message: " is already in the game" }
end

app/models/player_skill.rb
class PlayerSkill < ApplicationRecord

    belongs_to :player, :class_name => "User"
    belongs_to :skill

    # validates :skill_id, presence: true, :uniqueness => 
    # { :scope => :skill_id, message: " is already added to player" }

    # validates :level, numericality: { greater_than: 0, less_than_or_equal_to 10}

end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :player_skill, :foreign_key => 'skill_id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
   belongs_to :player_game, :foreign_key => 'player_id', optional: true

    has_many :games, :foreign_key => 'host_id'
    

    validates :name, uniqueness: true
    validates :name, :age, presence: true

    validates :age, numericality: {greater_than_or_equal_to: 18, message: "You must be 18 or older to sign up"}



    has_many :player_skills, :foreign_key => 'player_id'
    has_many :skills, :class_name => 'User', through: :player_skills


    has_many :user_reviews 
    enum gender: [:undisclosed, :female, :male, :other]

end

app/models/user_review.rb
class UserReview < ApplicationRecord
    belongs_to :user
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController

    def index
        @courts = Court.all

        @chicago_courts = Court.chicago_ball_parks
    end
    
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    before_action :find_game, only: [:show, :edit, :update, :destroy]

    def index
        @games = Game.all
        @courts = Court.all
    end

    def show
        
        @players = @game.players
        
        @courts = Court.all
    end

    def new
        @game = Game.new
        @courts = Court.all
        @users = User.all
        # @chicago_courts = Court.chicago_ball_parks
        
    end

    def create
        @game = Game.new(game_params)
    

        if @game.save
            redirect_to game_path(@game)
        else
            flash[:errors] = @game.errors.full_messages
            redirect_to new_game_path(@game)
        end

    end

    def edit
       @users = User.all
       @courts = Court.all
       @chicago_courts = Court.chicago_ball_parks
    end

    def update
        @game.update(game_params)

        if @game.save 
            redirect_to game_path(@game)
        else 
            flash[:errors] = @game.errors.full_messages
            render :edit
        end
    end


    def destroy
        
        @game.delete

        redirect_to games_path
    end



    private

    def find_game
        @game = Game.find(params[:id])
      end

    def game_params
        params.require(:game).permit(:name, :host_id, :court_id, :date, :time, :player_count)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(:name => params[:name])
        session[:user_id] = user.id

        redirect_to root_path
    end

    def destroy
        reset_session

        redirect_to login_path
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path(@user)
        end
    end

    def edit
    #    @user = User.find(user_params)
    end

    def update
        
        @user.update(user_params)
        
        if @user.save 
            redirect_to user_path(@user)
        else 
            render :edit
        end
    end


    def show
        # @user = User.find(params[:id])
        @player_skills = @user.player_skills
        @user_reviews = @user.user_reviews
    end

    def destroy
        
        @user.delete

        redirect_to users_path
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit( :name, :age, :game_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def new
        @user = User.new
    end

    def create
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/player_games_helper.rb
module PlayerGamesHelper
end

app/helpers/player_skills_helper.rb
module PlayerSkillsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Games/edit.html.erb
<div class="container overflow-auto">
<div class="row">
    <div class="col-md-12" style="text-align: center">
    <h1><%= @game.name %></h1>
    <p style="color: yellow">Edit this game</p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">

        <%= form_for (@game) do |f|%>
            <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
            <p class="errors" ><%= error %></p>
            <% end %>
        <% end %>

        <%= f.label :name %><br>
        <%=f.text_field :name %>

    </div>

    <div class="col-md-6">

        <%= f.label :host_id %> <br>
        <%= f.collection_select :host_id, @users, :id, :name %>

    </div>

</div>
<div class="row">

    <div class="col-md-6">
        <%= f.label :court_id %><br>
        <%= f.collection_select :court_id, @courts, :id, :name %>
    </div>
   
    <div class="col-md-6">
        <%= f.label :date %><br>
        <%=f.date_field :date %>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <%= f.label :time %><br>
        <%= f.time_select :time, {discard_minute: true, ampm: true} %>
    </div>

    <div class="col-md-6">
        <%= f.label :player_count %><br>
        <%=f.number_field :player_count%>
        
    </div>
</div>
<div class="row">
    <div class="col-md-12">
    <%=f.submit%>
    </div>
</div>
    <%end%>

</div>

app/views/Games/index.html.erb
<div class="container">
<h1>Games In Your City</h1>


<% if @games.count == 0 %>
  <p>Let's Hoop <%= link_to 'Start a Game!', new_game_url %></p>
<% end %>

<ul>
   <% @games.each do |game| %>
    <li> <%= link_to game.name, game_path(game) %></li> <br><br>
   <% end %>
</ul>

</div>



   

app/views/Games/new.html.erb
<div class="container">

<div class="row">
    <div class="col-md-12">
    <h2>Host Your Own Game</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">

        <%= form_for (@game) do |f|%>
            <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
            <p class="errors" ><%= error %></p>
            <% end %>
        <% end %>

        <%= f.label :name %><br>
        <%=f.text_field :name %>

    </div>

    <div class="col-md-6">

        <%= f.label :host_id %> <br>
        <%= f.collection_select :host_id, @users, :id, :name %>

    </div>

</div>
<div class="row">

    <div class="col-md-6">
        <%= f.label :court_id %><br>
        <%= f.collection_select :court_id, @courts, :id, :name %>
    </div>
   
    <div class="col-md-6">
        <%= f.label :date %><br>
        <%=f.date_field :date %>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <%= f.label :time %><br>
        <%= f.time_select :time, {discard_minute: false, ampm: true} %>
    </div>

    <div class="col-md-6">
        <%= f.label :player_count %><br>
        <%=f.number_field :player_count%>
        
    </div>
</div>
<div class="row">
    <div class="col-md-12">
    <%=f.submit%>
    </div>
</div>
    <%end%>

</div>

app/views/Games/show.html.erb
<div class="container overflow-auto">
<div class="row">
    <div class="col-md-12" style="text-align: center">
    <h1><%= @game.name %></h1>
    </div>
</div>

    <div class="row">
        <div class="col-md-12">
            <p>This Game needs <%= @game.player_count %> players</p>
        </div>
    </div>

  <div class="row">
        <div class="col-md-6">
            <h4>Location:</h4><br>
            

        </div>
        <div class="col-md-6">
            <p>Playing at  <%= @game.court.name %> located <%= @game.court.location %> </p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
             <h4>Date:</h4><br>
            
        </div>
        <div class="col-md-6">
            
            <p>Playing on <%= @game.clean_date %> at <%= @game.clean_time %> </p>
            
        </div>
    </div>

    
    <div class="row">
        <div class="col-md-6" >

            <h3>Players:</h3> 
                
        </div>
        <div class="col-md-6" >
                <ul>
                    <li><%= link_to @game.user.name, user_path(@game.user) %> 
                    <% @players.each do |player| %>
                    <li><%= link_to player.name, user_path(player) %></li>
                    <% end %>
                </ul>
        </div>
    </div>




    <div class="row">
        <div class="col-md-4" style="text-align: center">
            <%= link_to "Edit This Game", edit_game_path(@game) %> <br><br>
            <%= link_to "Add Players", new_player_game_path %>
            <p>This Game is looking for <%= @game.players_left%> more players</p>
            <p>This Game has <%= @game.pg_count %> players</p>
        </div>

        
            <div class="col-md-4" style="text-align: center">
                <%= link_to "Check Out Other Games", games_path %>
            </div>
        
    
        <div class="col-md-4" style="text-align: center">
            <%= form_for(@game, :method => :delete, :remote => true) do |f| %>
            <%= f.submit :value => "Delete Game" %>
            <% end %>
        </div>
    </div>

  
    
</div>

app/views/courts/index.html.erb
<iframe
  width="100%" 
  height = "800vh" 
  frameborder="0"
  style= "border:0"
  center: {lat: 41.8781, lng: -87.6298},
	zoom: 11,
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAU4hxS3-1zSOzuPlRz5al2tsDK60Y4EeU
    &q=Chicago" allowfullscreen>
</iframe>

app/views/skills/new.html.erb
<div class="container">
<h1>Create A New Skill</h1>


<%= form_for (@skill) do |f|%>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p style = " color : red " ><%= error %></p>
    <% end %>
   <% end %>

    <%= f.label :name%>
    <%=f.text_field :name %><br>
    
    <%= f.label :description%>
    <%=f.text_field :description%><br>

    <%=f.submit%><br>

<%end%>

</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="new_user">

    <h1>EDIT PAGE FOR USER</h1>


        <%= form_for (@user) do |f|%>

            <%= f.label :name%>
            <%=f.text_field :name %><br>
            
            <%= f.label :age%>
            <%=f.number_field :age%><br>

            <%=f.submit%><br>

        <%end%>
    </div>

</div>

app/views/users/index.html.erb
<div class="container overflow-auto">

<h1 class="user_title">Players Signed Up</h1>

<div >
<% @users.each do |user| %>
    <h3 class="user_names my-2"><%= link_to user.name, user_path(user), class:"btn btn-home btn-primary" %></h3>
    <br>
<% end %>

</div>

</div>

app/views/users/new.html.erb
<div class="container">
    <div class="new_user">
        <div class="row justify-content-md-center">

        <h1>Sign up to ball</h1>
        <%= form_for (@user) do |f|%>

        <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
                <p class="errors"><%= error %></p>
            <% end %>
        <% end %>
            <div class="col col-md-6">
                <%= f.label :name%><br>
                <%=f.text_field :name %><br>
            </div>
        
            <div class="col col-md-6">
                <%= f.label :age%>
                <%=f.number_field :age%><br>
            </div>
            <div class="col col-lg-2">
                <%=f.submit%><br>
            </div>

        <%end%>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container overflow-auto">
<div class="new_user">
<h1><%= @user.name.capitalize %></h1>

<h5>Age: <%= @user.age %></h5>


<!--<h3><%= @user.name.capitalize %>'s Games</h3>


<h3><%= @user.name.capitalize %>'s Abilities</h3>
<ul>
    <% @user.player_skills.each do |player_skill| %>
    <li><%= player_skill.skill.name %> Level: <%= player_skill.level %></li>
    <% end %>
</ul>

<h3><%= @user.name.capitalize %>'s Reviews</h3>
<ul>
    <% @user.user_reviews.each do |user_review| %>
        <li> 
            <strong><%= user_review.title %></strong> 
            <br><br> 
            <%= user_review.body %>
            <br><br>Rating: 
            <%= user_review.rating %>/10
        </li>
    <% end %>
</ul> -->

<%= link_to "Edit yourself", edit_user_path(@user) %> <br><br>

<%= form_for(@user, :method => :delete, :remote => true) do |f| %>
<%= f.submit :value => "Delete User" %>
<% end %>

<p><%= link_to "View Other Players", users_path %> </p>
<br><br>
</div>
</div>